export const SET_TOKEN = "SET_TOKEN";
export const SET_PARTICIPANT_ID = "SET_PARTICIPANT_ID";

export const VALIDATE_ACCESS_TOKEN_START = "VALIDATE_ACCESS_TOKEN_START";
export const VALIDATE_ACCESS_TOKEN_SUCCESS = "VALIDATE_ACCESS_TOKEN_SUCCESS";
export const VALIDATE_ACCESS_TOKEN_FAILED = "VALIDATE_ACCESS_TOKEN_FAILED";

export const GET_PARTICIPANT_DATA_START = "GET_PARTICIPANT_DATA_START";
export const GET_PARTICIPANT_DATA_SUCCESS = "GET_PARTICIPANT_DATA_SUCCESS";
export const GET_PARTICIPANT_DATA_FAILED = "GET_PARTICIPANT_DATA_FAILED";

export const GET_NFT_CERTIFICATE_START = "GET_NFT_CERTIFICATE_START";
export const GET_NFT_CERTIFICATE_SUCCESS = "GET_NFT_CERTIFICATE_SUCCESS";
export const GET_NFT_CERTIFICATE_FAILED = "GET_NFT_CERTIFICATE_FAILED";

export const GET_NFT_DATA_START = "GET_NFT_DATA_START";
export const GET_NFT_DATA_SUCCESS = "GET_NFT_DATA_SUCCESS";
export const GET_NFT_DATA_FAILED = "GET_NFT_DATA_FAILED";
